### ISSUE TITLE
Libzip fails Cmake configuration with -DBUILD_TOOLS=OFF in GraphicsMagick oss-fuzz builds

### ISSUE THREAD

**Issue by bobfriesenhahn** [nih-at/libzip#485]
**CMake Error**

```
-- Found ZLIB: /work/lib/libz.a (found suitable version "1.3.1.1", minimum required is "1.1.2")
-- Found BZip2: /work/lib/libbz2.a (found version "1.0.6")
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Looking for lzma_auto_decoder in /work/lib/liblzma.a
-- Looking for lzma_auto_decoder in /work/lib/liblzma.a - found
-- Looking for lzma_easy_encoder in /work/lib/liblzma.a
-- Looking for lzma_easy_encoder in /work/lib/liblzma.a - found
-- Looking for lzma_lzma_preset in /work/lib/liblzma.a
-- Looking for lzma_lzma_preset in /work/lib/liblzma.a - found
-- Found LibLZMA: /work/lib/liblzma.a (found suitable version "5.7.1", minimum required is "5.2")
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Found zstd: /work/lib/libzstd.a (Required is at least version "1.4.0")
CMake Warning at CMakeLists.txt:278 (message):
  -- neither Common Crypto, GnuTLS, mbed TLS, OpenSSL, nor Windows
  Cryptography found; AES support disabled


-- Configuring done (9.5s)
CMake Error: INSTALL(EXPORT) given unknown export "libzip-bin-targets"
-- Generating done (0.0s)
```

**libzip Version**

Latest git version as of February 16, 2025.

Interestingly, this problem (and possibly another) appears to have started after Feburary 13, according to oss-fuzz builds. It is not clear if this is due to a change in libzip, or in the oss-fuzz prepared environment/toolchain. See https://oss-fuzz-build-logs.storage.googleapis.com/index.html#graphicsmagick for oss-fuzz build history.

**Operating System and Compiler**

Ubuntu 22.04 LTS and Clang compiler as supported by Google oss-fuzz building.

These options were passed to CMake (and failed):

```
        cmake \
            -DBUILD_SHARED_LIBS=off \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_C_COMPILER=$CC \
            -DCMAKE_C_FLAGS="$CFLAGS -fPIC" \
            -DCMAKE_INSTALL_PREFIX=$WORK \
            -DCMAKE_VERBOSE_MAKEFILE:BOOL=TRUE \
            -DBUILD_DOC=OFF \
            -DBUILD_EXAMPLES=OFF \
            -DBUILD_OSSFUZZ=OFF \
            -DBUILD_REGRESS=OFF \
            -DBUILD_TOOLS=OFF \
            -DENABLE_GNUTLS=OFF \
            -DENABLE_MBEDTLS=OFF \
            -DENABLE_OPENSSL=OFF \
            -DHAVE_CRYPTO=OFF  \
            "${SRC}/libzip
        make -j$(nproc)
        make install
```
but these options do not cause a hard failure:

```
        cmake \
            -DBUILD_SHARED_LIBS=off \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_C_COMPILER=$CC \
            -DCMAKE_C_FLAGS="$CFLAGS -fPIC" \
            -DCMAKE_INSTALL_PREFIX=$WORK \
            -DCMAKE_VERBOSE_MAKEFILE:BOOL=TRUE \
            -DBUILD_DOC=OFF \
            -DBUILD_EXAMPLES=OFF \
            -DBUILD_OSSFUZZ=OFF \
            -DBUILD_REGRESS=OFF \
            -DBUILD_TOOLS=ON \
            -DENABLE_GNUTLS=OFF \
            -DENABLE_MBEDTLS=OFF \
            -DENABLE_OPENSSL=OFF \
            -DHAVE_CRYPTO=OFF  \
            "${SRC}/libzip"
        make -j$(nproc)
        make install
```

**Autodetected Configuration**
Attach `CmakeCache.txt` from your build directory. This list everything `cmake` detected on your system.

This is the `CmakeCache.txt` from the build directory. 

[CMakeCache.txt](https://github.com/user-attachments/files/18816363/CMakeCache.txt)

**Comment by 0-wiz-0** [comment]
I think I fixed this in https://github.com/nih-at/libzip/commit/8d8a9ef076abb45f99ddbebad57715d26c77a98a or is there more to do here?

**Comment by bobfriesenhahn** [comment]
I don't know if there is more to do.  I see that libzip itself was failing its oss-fuzz build (https://oss-fuzz-build-logs.storage.googleapis.com/index.html#libzip) with the exact same error.

Given that preparing a GraphicsMagick oss-fuzz build seems to take an hour (or hours) on my laptop, it seems easiest to wait to see if libzip's own oss-fuzz build starts working again.

**Comment by bobfriesenhahn** [comment]
Now that I look at the changeset, it seems that it is side-stepping the underlying issue that sometimes one only wants to build a library, but without tools.  The build was successful with original options on 2/13/2025.  If the option to build without tools was working before, why does it not work now?

**Comment by 0-wiz-0** [comment]
Good idea, let's wait for the next run. Thanks for the report!

**Comment by bobfriesenhahn** [comment]
I made a similar change to the GraphicsMagick oss-fuzz build (so that it works again), but surely this is an issue with libzip's Cmake build, and not with the oss-fuzz build script (which acted only as the messenger).

**Comment by 0-wiz-0** [comment]
The changes we did on Feb 13 don't look related, so I assume changes on the ossfuzz side.
I don't see the problem with the change - if you turn off the tools, you can't run the regression tests.
ossfuzz wants to run them, so we enable the tools build for it.
You can build just the library (without the tools, and without running the tests).

**Comment by bobfriesenhahn** [comment]
I expect that the issue is with Google's off-fuzz software (infrastructure and compiler) introduced after the 2/13/2025 build.  I believe this because I see many projects now failing which were succeeding prior to that date.

Certainly the Clang compiler became more picky (the pre-processor part). I had to change the zlib oss-fuzz build as well, but for a different reason.

**Comment by bobfriesenhahn** [comment]
As a reminder, this bug report is about libzip not compiling under the oss-fuzz environment without -DBUILD_TOOLS=ON.  It is likely true that libzip's own oss-fuzz testing requires those tools.  But GraphicsMagick's oss-fuzz testing does not require the tools.

**Comment by 0-wiz-0** [comment]
I don't understand why you do your own fuzzing of libzip in a way that uses libzip's fuzzing setup.

libzip does its own fuzzing with ossfuzz.

If you want to run the libzip regression tests OR do libzip fuzzing, you need to turn on the build of the tools.

**Comment by bobfriesenhahn** [comment]
A problem I fixed in GraphicsMagick's oss-fuzz build was a failure to build zlib.  The Clang compiler has become picky about include file syntax. The error which was produced is:

```
zconf.h' file not found with <angled> include; use "quotes" instead
```

In response to a message I just saw, the GraphicsMagick oss-fuzz build builds libzip because it is a linkage dependency.  It is part of a large build.  The GraphicsMagick oss-fuzz does not replicate the fuzzing that libzip does on its own.  Instead it is only using libzip for the reader for one file format which uses libzip as part of its implementation.

**Comment by 0-wiz-0** [comment]
I misread the warning and overlooked the error later in the ossfuzz log - I think https://github.com/nih-at/libzip/commit/df363f35b9c4164440cf62dc10ae3173fa22f6f5 should fix this.

**Comment by bobfriesenhahn** [comment]
This new fix seems likely to work.  I will wait until tomorrow and verify that I can successfully use -DBUILD_TOOLS=OFF in GraphicsMagick's oss-fuzz build.

**Comment by bobfriesenhahn** [comment]
The oss-fuzz builds clone fresh from the master repository (https://github.com/nih-at/libzip.git) for each build.  Unfortunately, I found that the GraphicsMagick oss-fuzz build still fails to build libzip without -DBUILD_TOOLS=ON:

```
-- Found zstd: /work/lib/libzstd.a (Required is at least version "1.4.0")
CMake Warning at CMakeLists.txt:278 (message):
  -- neither Common Crypto, GnuTLS, mbed TLS, OpenSSL, nor Windows
  Cryptography found; AES support disabled


-- Configuring done (9.8s)
CMake Error: INSTALL(EXPORT) given unknown export "libzip-bin-targets"
-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
ERROR:__main__:Building fuzzers failed.
```

Indeed, I see that the 2/17/2025 build of libzip (https://oss-fuzz-build-logs.storage.googleapis.com/index.html#libzip) is still failing.

**Comment by 0-wiz-0** [comment]
I've commented out the new export code from Friday completely.

I cannot reproduce this at all locally, so this is hard to test.

**Comment by dillof** [comment]
Thanks for the bug report.  We found and fixed the bug now and reenabled the separate cmake file.
